name: test

on:
  schedule:
    # Run every minute
    - cron: '*/5 * * * *' 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print current time
        run: echo "This job ran at $(date)"
